development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options: {}
  options:
    raise_not_found_error: true

test:
  clients:
    default:
      database: mygym_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options: {}
  options:
    raise_not_found_error: true
